server:
  port: 8090

logging: 
  level:
    root: INFO
    com.example.demo: DEBUG

spring:
  application:
    name: Demo-Security
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      # disable jdbc metadata (avoid the exception: PgConnection.createClob() is not yet implemented)
      hibernate.temp.use_jdbc_metadata_defaults: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

app:
  security:
    authentication:
      jwt:
        # https://www.base64encode.org/
        secret-key: ZGVtbw== 
        expiration-in-seconds: 86400 

  
